// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import HelloController from './hello_controller'
application.register('hello', HelloController)

import NavbarController from './navbar_controller'
application.register('navbar', NavbarController)

import Carousel from 'stimulus-carousel'
application.register('carousel', Carousel)

import ScrollReveal from 'stimulus-scroll-reveal'
application.register('scroll-reveal', ScrollReveal)

import ReadMore from 'stimulus-read-more'
application.register('read-more', ReadMore)

import ScrollToController from './scroll_to_controller'
application.register('scroll-to', ScrollToController)

import FlashController from './flash_controller'
application.register('flash', FlashController)

import ModalController from './modal_controller'
application.register('modal', ModalController)

import LazyController from './lazy_controller'
application.register('lazy', LazyController)

import RailsNestedForm from './nested_form_controller'
application.register('nested-form', RailsNestedForm)

import Sortable from './sortable_controller'
application.register('sortable', Sortable)

import Slimselect from './slimselect_controller'
application.register('slimselect', Slimselect)

import FormController from './form_controller'
application.register('form', FormController)

import MediaPickerController from './media_picker_controller'
application.register('media-picker', MediaPickerController)

import SelectableController from './selectable_controller'
application.register('selectable', SelectableController)

import BulkImportController from './bulk_import_controller'
application.register('bulk-import', BulkImportController)
