require:
  - rubocop-rspec
  - rubocop-rails

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Style/SymbolProc:
  Exclude:
    - 'app/**/*' # Exclude the warning in all files under the app directory
    - 'spec/**/*' # Exclude the warning in all files under the spec directory
